---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/signup/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/signup/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/signup/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/signup":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/login":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/logout":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
